apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: python
build:
  insecureRegistries: ["192.168.0.36:32000"]
  artifacts:
  - image: 192.168.0.36:32000/quire
    kaniko:
      insecure: true
      skipTLS: true
      dockerfile: Dockerfile
  cluster: {}

deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
